#! zsh

local -a newbins

# go
[[ -z $GOPATH ]] && export GOPATH=~/.go
newbins+=(~/.go/bin)

# haskell
newbins+=(~/.cabal/bin ~/Library/Haskell/bin)

# ooc
if (( $+commands[rock] )); then
	export -UT OOC_LIBS ooc_libs
	ooc_libs=(/usr/local/Cellar/rock/*(N) $XDG_DATA_HOME/ooc)
	newbins+=($XDG_DATA_HOME/ooc/sam)
fi

# ruby
newbins+=(~/.gem/ruby/*/bin(N))

# perl
export PERL_LOCAL_LIB_ROOT="$HOME/perl5:$PERL_LOCAL_LIB_ROOT"
export PERL_MB_OPT="--install_base '$HOME/perl5'";
export PERL_MM_OPT="INSTALL_BASE=$HOME/perl5";
export PERL5LIB="$HOME/perl5/lib/perl5:$HOME/.perllibs:$PERL5LIB";
newbins+=(~/perl5/bin)

# php
# I have no idea why Composer decided that the right place to install global
# packages is $XDG_CONFIG_HOME. It *clearly* should be $XDG_DATA_HOME. But
# there you go, I guess.
newbins+=($XDG_CONFIG_HOME/composer/vendor/bin)

# python
export -UT PYTHONPATH pythonpath

path=($newbins $path)
