#! zsh
typeset -A ZINIT
ZINIT[HOME_DIR]=$ZINIT_HOME
ZINIT[ZCOMPDUMP_PATH]=$XDG_CACHE_HOME/zsh/zcompdump

if [[ ! -f $ZINIT_HOME/bin/zinit.zsh ]]; then
	git clone https://github.com/zdharma/zinit $ZINIT_HOME/bin
	zcompile $ZINIT_HOME/bin/zinit.zsh
fi
source $ZINIT_HOME/bin/zinit.zsh
load=light

zinit $load willghatch/zsh-saneopt

zinit $load mafredri/zsh-async
zinit $load rupa/z

if (( $+commands[starship] )); then
	source <(starship init zsh --print-full-init)
else
	zinit $load sindresorhus/pure
fi

zinit pack:no-dir-color-swap for ls_colors

zinit ice silent wait:1 atload:_zsh_autosuggest_start
zinit $load zsh-users/zsh-autosuggestions

zinit ice blockf; zinit $load zsh-users/zsh-completions

zinit ice silent wait:1; zinit $load mollifier/cd-gitroot
zinit ice silent wait:1; zinit $load micha/resty
zinit ice silent wait:1; zinit $load supercrabtree/k

zinit ice silent wait!1; zinit $load zdharma/fast-syntax-highlighting
