source $ZDOTDIR/zplugin
for f in $ZDOTDIR/interactive/*(N); source $f

autoload -Uz compinit zrecompile
compinit -d $XDG_CACHE_HOME/zsh/zcompdump
([[ $_comp_dumpfile.zwc -nt $_comp_dumpfile ]] || zcompile $_comp_dumpfile) &!

[[ -o login ]] && for f in $ZDOTDIR/interactive+login/*(N); source $f

# If zsh init ends with a failing command (like a conditional) the prompt will
# show the "error" colour on first launch. To avoid this, we simply end with a
# true command:
true
