#! zsh
alias ls='ls -F --color=auto'
alias lsl='ls -lh'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias pseudo=sudo
if (( $+commands[xdg-open] )); then
	alias ]=xdg-open
else
	alias ]=open
fi
alias cdu=cd-gitroot

# make sure ELinks can detect when it's in tmux
alias elinks="STY= elinks"

(( $+commands[hub] )) && alias git=hub
