#! zsh
_direnv_hook() {
	trap -- '' SIGINT
	emulate zsh -c "$(direnv export zsh)"
	trap - SIGINT
}

typeset -ag precmd_functions chpwd_functions
if (( $+commands[direnv] )); then
	[[ -z ${precmd_functions[(r)_direnv_hook]} ]] && precmd_functions+=(_direnv_hook)
	[[ -z ${chpwd_functions[(r)_direnv_hook]} ]] && chpwd_functions+=(_direnv_hook)
fi
