#! zsh

[[ ! -d $ZINIT[HOME_DIR] ]] && mkdir -p $ZINIT[HOME_DIR]
if [[ ! -d $ZINIT[BIN_DIR]/.git ]]; then
	git clone https://github.com/zdharma-continuum/zinit.git $ZINIT[BIN_DIR]
	zcompile $ZINIT[BIN_DIR]/zinit.zsh
fi
source $ZINIT[BIN_DIR]/zinit.zsh
load=light

zinit $load willghatch/zsh-saneopt

zinit $load mafredri/zsh-async
zinit $load rupa/z

if (( $+commands[starship] )); then
	source <(starship init zsh --print-full-init)
	autoload starship_pure_title_precmd starship_pure_title_preexec
	precmd_functions+=(starship_pure_title_precmd)
	preexec_functions+=(starship_pure_title_preexec)
else
	zinit $load sindresorhus/pure
fi

if (( $+commands[vivid] )); then
	export LS_COLORS=$(vivid generate molokai)
else
	zinit pack:no-dir-color-swap for ls_colors
fi

zinit wait lucid light-mode for \
	mollifier/cd-gitroot \
	atinit"dot-zsh-compinit" \
		zdharma-continuum/fast-syntax-highlighting \
	atload"_zsh_autosuggest_start" \
		zsh-users/zsh-autosuggestions \
	blockf atpull'zinit creinstall -q .' \
		zsh-users/zsh-completions
